#!/bin/sh
set -e

dir=/usr/src/php

usage() {
	echo "usage: $0 COMMAND"
	echo
	echo "Manage php source tarball lifecycle."
	echo
	echo "Commands:"
	echo "   extract  extract php source tarball into directory $dir if not already done."
	echo "   delete   delete extracted php source located into $dir if not already done."
	echo
}

case "$1" in
	extract)
		mkdir -p "$dir"
		if [ ! -f "$dir/.docker-extracted" ]; then
			tar -Jxf /usr/src/php.tar.xz -C "$dir" --strip-components=1
##<patches>##
			if [ -f /usr/src/php_patches.tar.xz ]; then
				mkdir -p "$dir/patches"
				tar -Jxf /usr/src/php_patches.tar.xz -C "$dir/patches"
				for patch in `sed '/^\s*$/d' $dir/patches/series`; do
					echo '===== Applying patch '"$dir/patches/$patch"' ====='
					patch -fruN -p 1 -d "$dir" < "$dir/patches/$patch"
				done
			fi
##</patches>##
			touch "$dir/.docker-extracted"
		fi
		;;

	delete)
		rm -rf "$dir"
		;;

	*)
		usage
		exit 1
		;;
esac
